vich_uploader:
    db_driver: orm

    mappings:
        project_image:
            uri_prefix: /images/project
            upload_destination: '%kernel.project_dir%/public/images/project'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
